[variables]
# Node.js version - using LTS version compatible with Astro 5.x
NODE_VERSION = "20"
# Build optimization
NODE_ENV = "production"
# Astro specific optimizations
ASTRO_TELEMETRY_DISABLED = "1"

[phases.setup]
# Install Node.js and use system PNPM to avoid corepack signature issues
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
dependsOn = ["setup"]
# Cache PNPM store for faster builds
cacheDirectories = [".pnpm-store", "node_modules"]
cmds = [
  "pnpm config set store-dir .pnpm-store",
  "pnpm install --frozen-lockfile --prefer-offline"
]

[phases.build]
dependsOn = ["install"]
# Cache Astro artifacts for incremental builds
cacheDirectories = ["dist", ".astro"]
cmds = [
  # use pnpm exec to ensure the local Astro CLI is in PATH
  "pnpm exec astro build"
]

[start]
# Serve the built static files
cmd = "pnpm preview --host 0.0.0.0 --port $PORT"

[staticAssets]
# Astro builds to dist/ directory
dir = "dist"
