[variables]
# Node.js version - using LTS version compatible with Astro 5.x
NODE_VERSION = "20"
# Build optimization
NODE_ENV = "production"
# Astro specific optimizations
ASTRO_TELEMETRY_DISABLED = "1"

[phases.setup]
# Install Node.js and use system PNPM to avoid corepack signature issues
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
# Cache PNPM store for faster builds
dependsOn = ["setup"]
cacheDirectories = [".pnpm-store", "node_modules"]
cmds = [
    "pnpm config set store-dir .pnpm-store",
    "pnpm install --frozen-lockfile --prefer-offline"
]

[phases.build]
# Type checking, linting, and building
dependsOn = ["install"]
cacheDirectories = ["dist", ".astro"]
cmds = [
    # Type check first to catch errors early
    "pnpm typecheck",
    # Lint and format check
    "pnpm lint",
    # Build the site
    "pnpm build"
]

[start]
# Serve the built static files
cmd = "pnpm preview --host 0.0.0.0 --port $PORT"

[staticAssets]
# Astro builds to dist/ directory
dir = "dist"